export const strings = {
  en: {
    appName: 'Invoice Bill Maker',
    tagline: 'Simple, Fast & Zero-Cost Billing for Retailers',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in with your Google account to manage your retail business billing seamlessly.',
    signInWithGoogle: 'Sign in with Google',
    demoLogin: 'Quick Demo Login',
    logout: 'Logout',
    dashboard: 'Dashboard',
    customers: 'Customers',
    buyers: 'Buyers',
    addCustomer: 'Add Customer',
    addBuyer: 'Add Buyer',
    customerName: 'Customer Name',
    buyerName: 'Buyer Name',
    fullName: 'Full Name *',
    phoneNumber: 'Phone Number',
    address: 'Address / Location',
    save: 'Save',
    cancel: 'Cancel',
    saving: 'Saving...',
    loading: 'Loading...',
    noCustomersTitle: 'No Customers Yet',
    noCustomersDesc: 'Tap the + button below to add your first customer and start tracking sales.',
    noBuyersTitle: 'No Buyers / Suppliers Yet',
    noBuyersDesc: 'Tap the + button below to add your first supplier/buyer for purchase tracking.',
    searchPlaceholder: 'Search by name or phone...',
    refresh: 'Pull to refresh',
    welcomeUser: 'Hello,',
    quickOverview: 'Quick Overview',
    totalCustomers: 'Total Customers',
    totalBuyers: 'Total Buyers',
    readyForInvoices: 'Increment 1 Active',
    activeSubtext: 'Core Customer & Buyer Directory is ready. Invoices will be added next!',
    errorRequired: 'Name is required.',
    errorSave: 'Failed to save. Please try again.',
    errorFetch: 'Failed to load data. Please pull down to retry.',
    customerDetailsPlaceholder: 'Customer details and transaction history will be available in Increment 2.',
  },
  gu: {
    appName: 'ઈનવોઈસ બિલ મેકર',
    tagline: 'વેપારીઓ માટે સરળ, ઝડપી અને ફ્રી બિલિંગ',
    loginTitle: 'સ્વાગત છે',
    loginSubtitle: 'તમારા બિઝનેસ બિલિંગ માટે ગૂગલ એકાઉન્ટ વડે લોગિન કરો.',
    signInWithGoogle: 'ગૂગલ વડે સાઇન ઇન કરો',
    demoLogin: 'ઝડપી ડેમો લોગિન',
    logout: 'લૉગ આઉટ',
    dashboard: 'ડેશબોર્ડ',
    customers: 'ગ્રાહકો (Customers)',
    buyers: 'વેપારીઓ (Buyers)',
    addCustomer: 'ગ્રાહક ઉમેરો',
    addBuyer: 'વેપારી ઉમેરો',
    customerName: 'ગ્રાહકનું નામ',
    buyerName: 'વેપારીનું નામ',
    fullName: 'પૂરું નામ *',
    phoneNumber: 'મોબાઇલ નંબર',
    address: 'સરનામું',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    saving: 'સાચવી રહ્યું છે...',
    loading: 'લોડ થઈ રહ્યું છે...',
    noCustomersTitle: 'હજુ સુધી કોઈ ગ્રાહક નથી',
    noCustomersDesc: 'તમારો પ્રથમ ગ્રાહક ઉમેરવા માટે નીચે આપેલા + બટનને ટેપ કરો.',
    noBuyersTitle: 'હજુ સુધી કોઈ વેપારી નથી',
    noBuyersDesc: 'તમારો પ્રથમ ખરીદદાર/વેપારી ઉમેરવા માટે નીચે આપેલા + બટનને ટેપ કરો.',
    searchPlaceholder: 'નામ અથવા ફોન નંબરથી શોધો...',
    refresh: 'રિફ્રેશ કરવા ખેંચો',
    welcomeUser: 'નમસ્તે,',
    quickOverview: 'ઝડપી ઝાંખી',
    totalCustomers: 'કુલ ગ્રાહકો',
    totalBuyers: 'કુલ વેપારીઓ',
    readyForInvoices: 'ઇન્ક્રીમેન્ટ ૧ સક્રિય',
    activeSubtext: 'ગ્રાહક અને વેપારી ડાયરેક્ટરી તૈયાર છે. ઈનવોઈસ હવે પછી ઉમેરાશે!',
    errorRequired: 'નામ જરૂરી છે.',
    errorSave: 'સાચવવામાં નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    errorFetch: 'ડેટા લોડ કરવામાં નિષ્ફળ.',
    customerDetailsPlaceholder: 'ગ્રાહકની વિગતો અને ઇતિહાસ ઇન્ક્રીમેન્ટ ૨ માં ઉપલબ્ધ થશે.',
  },
};

// Default language: en
export const t = strings.en;
